### ISSUE TITLE
你这个咋用啊

### ISSUE THREAD

**Issue by a100488** [cn-src/swagger-document-ui#1]
你这个咋用啊

**Comment by cn-src** [comment]
这个需要配合springfox框架使用。或者静态部署dist里编译好的文件，再通过swagger-resources.json配置 swagger 规范的 api 地址，不过这个我还没正式测试过。

**Comment by a100488** [comment]
不是直接加个maven就行了吗

**Comment by cn-src** [comment]
配合 springfox 是这样的，springfox 有自己的 ui jar 包，这个项目仅仅只能替代 ui，所以真正的还是使用 springfox 框架。

**Comment by a100488** [comment]
![image](https://user-images.githubusercontent.com/12635040/48104371-33e92f00-e26e-11e8-8c14-258d04a3405c.png)
我项目里面有springfox

**Comment by a100488** [comment]
怎么替换啊
